### ISSUE TITLE
It doesn't works fine under cloudflared

### ISSUE THREAD

**Issue by edersong** [BaldissaraMatheus/Tasks.md#12] opened 2023-03-12 22:30 UTC
Locally, it works fine, but behind cloudflared it's not showing correctly

**Comment by boomam** [comment] 2023-03-15 13:27
What is the error you see @edersong - to note, I am not the developer of this project but I am familiar with cloudflared, so may be able to help.  
&nbsp;  
I would recommend however, that as this app does not have any login prompt or auth, to make sure you are putting something infront of it to help protect it, should you decide you need outside access via that method.  
[Authelia](https://www.authelia.com/) is great for that particular purpose.

**Comment by edersong** [comment] 2023-03-15 13:32
Thank you for the feedback, @BaldissaraMatheus 
Found that its failing the same way locally.
See below:

[2023-03-15 143000.png](https://user-images.githubusercontent.com/64137913/225323768-c2b1b904-f8b9-440a-b742-edbd32783a14.png)

**Comment by boomam** [comment] 2023-03-15 13:38
What are your various CF settings?  

### Tunnel
Dashboard->Zero Trust->Access->Tunnels->(click tunnel name)->Configure->Public Hostname->(Click hostname)->Configure->Additional application settings.

### SSL/TLS
Dashboard->DNS->SSL/TLS->Overview

### 'Speed'
Dashboard->DNS->Speed->Optimization

### Caching
Dashboard->DNS->Caching->Configuration

**Comment by BaldissaraMatheus** [comment] 2023-03-15 16:45
@edersong the picture you attached is running locally or under a cloudflare proxy?  It looks like it's failling to fetch the css files and I think it may be related to #15

When you run the container without passing a BASE_PATH variable, does it work?

**Comment by boomam** [comment] 2023-03-15 17:28
I just did a quick test my end, can confirm it works through a CF Tunnel fine. :-)

**Comment by edersong** [comment] 2023-03-17 09:34
Hello,
For me, without BASE_PATH variable, works locally, but not thru CF tunnel

**Comment by BaldissaraMatheus** [comment] 2023-05-09 20:28
Hey @edersong, sorry for taking to long for looking at this issue. Are you running it through Docker? Could you please share your docker file? I just tried running a tunnel both with a subpath and without it and it worked just fine

**Comment by BaldissaraMatheus** [comment] 2023-05-28 21:50
I'll close this issue for now since it seems to be caused by an incorrect setup, but if someone experience the same issue feel free to open it up again.

**Closed by BaldissaraMatheus** 2023-05-28 21:50 UTC
Labels: bug
